### ISSUE TITLE
Recipe Compile Errors

### ISSUE THREAD

**Issue by softamics** [Scalr/installer-ng#152]
I have received this on both CentOS 7 and Ubuntu 14.4.  Both are basic OS installs.  No other errors until this point.

    scalr-server-ctl show-attributes
    Starting Chef Client, version 12.0.3
    Compiling Cookbooks...
    
    ================================================================================
    Recipe Compile Error in /opt/scalr-server/embedded/cookbooks/scalr-server/attributes/default.rb
    ================================================================================
    
    ArgumentError
    -------------
    value must be enumerable
    
    Cookbook Trace:
    ---------------
      /opt/scalr-server/embedded/cookbooks/scalr-server/attributes/default.rb:20:in `block in from_file'
      /opt/scalr-server/embedded/cookbooks/scalr-server/attributes/default.rb:18:in `each'
      /opt/scalr-server/embedded/cookbooks/scalr-server/attributes/default.rb:18:in `from_file'
    
    Relevant File Content:
    ----------------------
    /opt/scalr-server/embedded/cookbooks/scalr-server/attributes/default.rb:
    
     13:
     14:  # IP Ranges #
     15:
     16:  # Identify all the ips that appear to be ours
     17:  node_ips = Set.new [node[:ipaddress]]
     18:  [:local_ipv4_addrs, :public_ipv4_addrs].each { |ipaddress_set|
     19:    begin
     20>>     node_ips.merge node[:cloud_v2][ipaddress_set]
     21:    rescue NoMethodError
     22:      # This will happen if the set doesn't exist
     23:      next
     24:    end
     25:  }
     26:
     27:  # Remove any nil IP.
     28:  node_ips.reject! { |ipaddress| ipaddress.nil?}
     29:
    
    
    Running handlers:
    [2015-04-21T00:21:04-04:00] ERROR: Running exception handlers
    Running handlers complete
    [2015-04-21T00:21:04-04:00] ERROR: Exception handlers complete
    [2015-04-21T00:21:04-04:00] FATAL: Stacktrace dumped to /opt/scalr-server/embedded/cookbooks/cache/chef-stacktrace.out
    Chef Client failed. 0 resources updated in 1.396338825 seconds
    [2015-04-21T00:21:04-04:00] ERROR: value must be enumerable
    [2015-04-21T00:21:04-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by krallin** [comment]
Hi there,

Two questions:

  + Can you provide the output of `ifconfig`? 
  + Can you add the following two lines before the line that is causing the issue, run the command, and report the output?

    puts node[:cloud_v2][ipaddress_set]
    puts node[:cloud_v2][ipaddress_set].class

Thanks!

**Comment by krallin** [comment]
Hi there,

This issue was fixed in https://github.com/Scalr/installer-ng/commit/0bb17ef583fd4a0db8ed1381517ba06b64e95db0

New packages will be issued shortly that should work properly 

Thanks for the report!
