### ISSUE TITLE
Ubuntu failing to fetch installer package

### ISSUE THREAD

**Issue by shammishailaj** [Scalr/installer-ng#162]
I am trying to install scalr OSS on an EC2 instance and after I run:

__sudo apt-get install -y scalr-server__

I am getting the following error:

_Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  scalr-server
0 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
Need to get 284 MB of archives.
After this operation, 934 MB of additional disk space will be used.
Fetched 284 MB in 37s (7,639 kB/s)
E: Failed to fetch https://packagecloud.io/scalr/scalr-server-oss/ubuntu/pool/trusty/main/s/scalr-server/scalr-server_5.3.2.oss~nightly.20150616043630.413.0780837.830aaad-1_amd64.deb  Hash Sum mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ubuntu@ip-_

**Comment by maratkomarov** [comment]
Please execute `apt-get update` before executing installation command and report whether it works for you.

**Comment by buzzy** [comment]
If it still does not work, try to clear your apt lists before doing the update:
sudo rm /var/lib/apt/lists/*

**Comment by shammishailaj** [comment]
Hello. I did a *wget* of the file _https://packagecloud.io/scalr/scalr-server-oss/ubuntu/pool/trusty/main/s/scalr-server/scalr-server_5.3.2.oss~nightly.20150616043630.413.0780837.830aaad-1_amd64.deb_ and then installed it using *dpkg -i*

**Comment by shammishailaj** [comment]
Anyways, just fyi, I had tried to do an *apt-get update* before reporting here and it did not work.
