### ISSUE TITLE
Role from non-scalr server NOT working

### ISSUE THREAD

**Issue by gugansankar** [Scalr/installer-ng#166]
There was no issue when I installed Scalr on my OpenStack server itself. It can retrieve the Role from Non-scalr server. 

   But the problem here is that , Moved Scalr service from OpenStack Server and created on separate public server. So here, Scalr will be in One Public IP and OpenStack Server in Seperate public IP and Under OpenStack, Cloud instances are in private IP. 

  When I create role on Scalr from Cloud Instance, Getting "Connection Timeout for port 8013". Yes, its true. One public server, shouldn't communicate with Private network of another public server until you wrote some routing rule. 

Please someone share idea on this.

Also one more query : Would Scalr support only if scalr installed on OpenStack Standalone server ???. 

Then What is the requirement of  OpenStack Hosted Scalr Model ?

**Comment by buzzy** [comment]
Please post your questions to the Scalr open source google groups.
https://groups.google.com/forum/#!forum/scalr-discuss

Github should only be used for actual issues/bugs with the code.
